version: "3.8"

services:
  console:
      container_name: jellyfin-console
      build:
        context: .
      image: catalyxcloud/jellyfin-console
      environment:
      - HOST_IP=${HOST_IP}
      ports:
          - 2022:80
      restart: unless-stopped
